### ISSUE TITLE
如何设置sdk路径

### ISSUE THREAD

**Issue by jp1017** [pengwei1024/apkReSign#2]
`java -jar apkReSign.jar` 出现这个：

![111](https://cloud.githubusercontent.com/assets/7868514/14521035/10698288-025a-11e6-9c71-eda8862837f1.jpg)

怎么设置sdk路径的？点确定后都消失了
:disappointed:

**Comment by pengwei1024** [comment]
目前只支持window平台呢，linux系统获取环境变量的方式不一样当时没有考虑到，只能以后优化了

**Comment by jp1017** [comment]
我是在win10下操作的啊，jdk，sdk都正常，环境变量设置成哪样呢？

**Comment by pengwei1024** [comment]
已经修复好了，你下载1.1.0版本吧

**Comment by pengwei1024** [comment]
@jp1017

**Comment by jp1017** [comment]
1.2.0版本可以选择了，感谢！
