### ISSUE TITLE
用android studio 生成的 key 签名

### ISSUE THREAD

**Issue by jp1017** [pengwei1024/apkReSign#3]
用android studio 生成的 key 签名失败
后期可否支持下？

**Comment by pengwei1024** [comment]
因为用android studio创建的key账号密码和default.keystore不一致，所以才失败的。你可以直接用jarsigner指令来完成签名的

**Comment by xingag** [comment]
应用市场上随便下一个apk，debug.keystore选择一栏，使用 Android Studio 生成的 keystore；重新签名后安装会报错，提示解析包出错。

**Comment by pengwei1024** [comment]
生成的keystore密码不一样啊，上面不是说了吗？只能用默认的keystore
